name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Démarrer le serveur local
        run: npx http-server -p 5500 &

      - name: Attendre que le serveur soit prêt
        run: npx wait-on http://localhost:5500

      - name: Lancer les tests Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config: baseUrl=http://localhost:5500

      - name: Générer le rapport de build (Mochawesome)
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json
          npx mochawesome-report-generator cypress/reports/report.json --reportDir cypress/reports

      - name: Uploader le rapport en artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports